### ISSUE TITLE
下游任务，摘要生成是否有代码呢？

### ISSUE THREAD

**Issue by duskfeng** [Hustcw/CLAP#1]

**Comment by Hustcw** [comment]
是指binary summarization吗？这个可以通过接一个decoder训练一个模型支持

**Comment by duskfeng** [comment]
> 是指binary summarization吗？这个可以通过接一个decoder训练一个模型支持

对的，主要是您的数据集没有公开，没法训练啊，是否有已经训练好的，或者是数据有没有开源呢？

**Comment by Hustcw** [comment]
数据集暂时因为合规性问题无法开源，可以尝试复现论文中的方法获取数据集，repo里提供了相应的prompt
