### ISSUE TITLE
您的模型是否太依赖字符串语义了？

### ISSUE THREAD

**Issue by duskfeng** [Hustcw/CLAP#2]
我在您的casestudy目录下的sha3.json中看到包括一行"39": "call    keccakf",一旦我将他改成"39": "call   rsa",或者"39": "call    bubbel sort",那么分类结果就百分之九十多的接近含有这个字符串的内容，这是否太不合理了。

**Comment by duskfeng** [comment]
![微信图片_20240415154452](https://github.com/Hustcw/CLAP/assets/79304356/d2d136cc-5357-4cd3-a751-cf7cc2cb0c8a)

**Comment by duskfeng** [comment]
![微信图片_20240415154509](https://github.com/Hustcw/CLAP/assets/79304356/1c3ef0fa-261a-48ef-8f02-30daae95b10c)

**Comment by duskfeng** [comment]
这些都是我只改变了调用函数名导致的？您是否有微调的下游模型和代码能提供给我使用

**Comment by Hustcw** [comment]
因为当前函数的语义是依赖于callee的，如果这里call的不是keccakf而是rsa或者bubble sort，那么这个函数的语义已经发生了变化，和sha没什么关系了

**Comment by duskfeng** [comment]
五十行的汇编代码，你不能说只要改了call后面的字符串，整个代码能变成毫不相关的语义吧。如果百分之三四十还合理但百分之90多是不是有问题啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hustcw/CLAP] 您的模型是否太依赖字符串语义了？ (Issue #2)




 
因为当前函数的语义是依赖于callee的，如果这里call的不是keccakf而是rsa或者bubble sort，那么这个函数的语义已经发生了变化，和sha没什么关系了

**Comment by Hustcw** [comment]
对这个函数而言，如果修改成了call rsa，它的decompile code如下所示：
```c
__int64 __fastcall sub_1AF3(__int64 a1, __int64 a2, int a3)
{
  int v3; // eax
  __int64 result; // rax
  unsigned int i; // [rsp+28h] [rbp-8h]
  int v7; // [rsp+2Ch] [rbp-4h]

  v7 = *(_DWORD *)(a1 + 204);
  for ( i = 0; ; ++i )
  {
    result = i;
    if ( (int)i >= a3 )
      break;
    v3 = *(_DWORD *)(a1 + 200);
    *(_DWORD *)(a1 + 200) = v3 + 1;
    *(_BYTE *)(a1 + v3) ^= *(_BYTE *)((int)i + a2);
    if ( v7 == *(_DWORD *)(a1 + 200) )
    {
      *(_DWORD *)(a1 + 200) = 0;
      rsa(a1);
    }
  }
  return result;
}
```
从以上decompile code可以看到判断这个函数语义最需要的就是这个callee，所以这其实并不算bad case

**Comment by duskfeng** [comment]
我看您的测试数据都只是截取了i64中的一个代码块作为一个json文件，我也试过无法使用多个代码块，是否有办法同时输入多个代码块呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hustcw/CLAP] 您的模型是否太依赖字符串语义了？ (Issue #2)




 
对这个函数而言，如果修改成了call rsa，它的decompile code如下所示：
 __int64 __fastcall sub_1AF3(__int64 a1, __int64 a2, int a3) {   int v3; // eax   __int64 result; // rax   unsigned int i; // [rsp+28h] [rbp-8h]   int v7; // [rsp+2Ch] [rbp-4h]   v7 = *(_DWORD *)(a1 + 204);   for ( i = 0; ; ++i )   {     result = i;     if ( (int)i &gt;= a3 )       break;     v3 = *(_DWORD *)(a1 + 200);     *(_DWORD *)(a1 + 200) = v3 + 1;     *(_BYTE *)(a1 + v3) ^= *(_BYTE *)((int)i + a2);     if ( v7 == *(_DWORD *)(a1 + 200) )     {       *(_DWORD *)(a1 + 200) = 0;       rsa(a1);     }   }   return result; }
 
从以上decompile code可以看到判断这个函数语义最需要的就是这个callee，所以这其实并不算bad case

**Comment by zeyugao** [comment]
您所说的代码块是指函数吗，现在是只支持单个函数作为输入

**Comment by duskfeng** [comment]
是的，如果只能输入单个函数那么就会出现很多调用外界函数名的语句，而且还无法获得外部函数的具体信息，只能依靠函数名来判断，这样感觉误差太大



---原始邮件---
发件人: "Elsa ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hustcw/CLAP] 您的模型是否太依赖字符串语义了？ (Issue #2)




 
您所说的代码块是指函数吗，现在是只支持单个函数作为输入

**Comment by Hustcw** [comment]
结合callee的方案可以进一步提升效果，我们目前使用CLAP进行代码搜索或者分类的效果也能做的不错
