### ISSUE TITLE
关于预训练

### ISSUE THREAD

**Issue by zzzzzzyc** [Hustcw/CLAP#5]
我看到测试数据都是一个代码块作为一个json文件，请问在对比学习预训练的时候，如果有很多代码块是怎么处理的呢，每一个代码块都和解释文本进行对比，还是选取部分？谢谢！

**Comment by zeyugao** [comment]
我们在训练的时候，一个函数是一个json文件，只会进行函数级别的对比学习。即一个函数只与一段解释文本进行对比，没有多代码块的场景

**Comment by zzzzzzyc** [comment]
> 我们在训练的时候，一个函数是一个json文件，只会进行函数级别的对比学习。即一个函数只与一段解释文本进行对比，没有多代码块的场景

感谢回复！如果一个二进制文件有很多函数，具体选择哪个函数与文本进行对比呢？

**Comment by zeyugao** [comment]
我们使用Data Engine章节的方法对二进制文件中的每一个函数都生成了对应的解释

**Comment by zzzzzzyc** [comment]
> 我们使用Data Engine章节的方法对二进制文件中的每一个函数都生成了对应的解释
好的明白了，谢谢你的解答！
